export const colors = {
    white: "rgb(var(--colors-white) / <alpha-value>)",
    black: "rgb(var(--colors-black) / <alpha-value>)",

    // These will be inverted in dark mode.
    "alpha-white": "rgb(var(--colors-alpha-white) / <alpha-value>)",
    "alpha-black": "rgb(var(--colors-alpha-black) / <alpha-value>)",

    current: "currentColor",
    transparent: "transparent",
    brand: {
        25: "rgb(var(--colors-brand-25) / <alpha-value>)",
        50: "rgb(var(--colors-brand-50) / <alpha-value>)",
        100: "rgb(var(--colors-brand-100) / <alpha-value>)",
        200: "rgb(var(--colors-brand-200) / <alpha-value>)",
        300: "rgb(var(--colors-brand-300) / <alpha-value>)",
        400: "rgb(var(--colors-brand-400) / <alpha-value>)",
        500: "rgb(var(--colors-brand-500) / <alpha-value>)",
        600: "rgb(var(--colors-brand-600) / <alpha-value>)",
        700: "rgb(var(--colors-brand-700) / <alpha-value>)",
        800: "rgb(var(--colors-brand-800) / <alpha-value>)",
        900: "rgb(var(--colors-brand-900) / <alpha-value>)",
        950: "rgb(var(--colors-brand-950) / <alpha-value>)",
    },
    gray: {
        25: "rgb(var(--colors-gray-light-mode-25) / <alpha-value>)",
        50: "rgb(var(--colors-gray-light-mode-50) / <alpha-value>)",
        100: "rgb(var(--colors-gray-light-mode-100) / <alpha-value>)",
        200: "rgb(var(--colors-gray-light-mode-200) / <alpha-value>)",
        300: "rgb(var(--colors-gray-light-mode-300) / <alpha-value>)",
        400: "rgb(var(--colors-gray-light-mode-400) / <alpha-value>)",
        500: "rgb(var(--colors-gray-light-mode-500) / <alpha-value>)",
        600: "rgb(var(--colors-gray-light-mode-600) / <alpha-value>)",
        700: "rgb(var(--colors-gray-light-mode-700) / <alpha-value>)",
        800: "rgb(var(--colors-gray-light-mode-800) / <alpha-value>)",
        900: "rgb(var(--colors-gray-light-mode-900) / <alpha-value>)",
        950: "rgb(var(--colors-gray-light-mode-950) / <alpha-value>)",
    },
    "gray-dark-alpha": {
        25: "rgb(var(--colors-gray-dark-alpha-25) / <alpha-value>)",
        50: "rgb(var(--colors-gray-dark-alpha-50) / <alpha-value>)",
        100: "rgb(var(--colors-gray-dark-alpha-100) / <alpha-value>)",
        200: "rgb(var(--colors-gray-dark-alpha-200) / <alpha-value>)",
        300: "rgb(var(--colors-gray-dark-alpha-300) / <alpha-value>)",
        400: "rgb(var(--colors-gray-dark-alpha-400) / <alpha-value>)",
        500: "rgb(var(--colors-gray-dark-alpha-500) / <alpha-value>)",
        600: "rgb(var(--colors-gray-dark-alpha-600) / <alpha-value>)",
        700: "rgb(var(--colors-gray-dark-alpha-700) / <alpha-value>)",
        800: "rgb(var(--colors-gray-dark-alpha-800) / <alpha-value>)",
        900: "rgb(var(--colors-gray-dark-alpha-900) / <alpha-value>)",
        950: "rgb(var(--colors-gray-dark-alpha-950) / <alpha-value>)",
    },
    error: {
        25: "rgb(var(--colors-error-25) / <alpha-value>)",
        50: "rgb(var(--colors-error-50) / <alpha-value>)",
        100: "rgb(var(--colors-error-100) / <alpha-value>)",
        200: "rgb(var(--colors-error-200) / <alpha-value>)",
        300: "rgb(var(--colors-error-300) / <alpha-value>)",
        400: "rgb(var(--colors-error-400) / <alpha-value>)",
        500: "rgb(var(--colors-error-500) / <alpha-value>)",
        600: "rgb(var(--colors-error-600) / <alpha-value>)",
        700: "rgb(var(--colors-error-700) / <alpha-value>)",
        800: "rgb(var(--colors-error-800) / <alpha-value>)",
        900: "rgb(var(--colors-error-900) / <alpha-value>)",
        950: "rgb(var(--colors-error-950) / <alpha-value>)",
    },
    warning: {
        25: "rgb(var(--colors-warning-25) / <alpha-value>)",
        50: "rgb(var(--colors-warning-50) / <alpha-value>)",
        100: "rgb(var(--colors-warning-100) / <alpha-value>)",
        200: "rgb(var(--colors-warning-200) / <alpha-value>)",
        300: "rgb(var(--colors-warning-300) / <alpha-value>)",
        400: "rgb(var(--colors-warning-400) / <alpha-value>)",
        500: "rgb(var(--colors-warning-500) / <alpha-value>)",
        600: "rgb(var(--colors-warning-600) / <alpha-value>)",
        700: "rgb(var(--colors-warning-700) / <alpha-value>)",
        800: "rgb(var(--colors-warning-800) / <alpha-value>)",
        900: "rgb(var(--colors-warning-900) / <alpha-value>)",
        950: "rgb(var(--colors-warning-950) / <alpha-value>)",
    },
    success: {
        25: "rgb(var(--colors-success-25) / <alpha-value>)",
        50: "rgb(var(--colors-success-50) / <alpha-value>)",
        100: "rgb(var(--colors-success-100) / <alpha-value>)",
        200: "rgb(var(--colors-success-200) / <alpha-value>)",
        300: "rgb(var(--colors-success-300) / <alpha-value>)",
        400: "rgb(var(--colors-success-400) / <alpha-value>)",
        500: "rgb(var(--colors-success-500) / <alpha-value>)",
        600: "rgb(var(--colors-success-600) / <alpha-value>)",
        700: "rgb(var(--colors-success-700) / <alpha-value>)",
        800: "rgb(var(--colors-success-800) / <alpha-value>)",
        900: "rgb(var(--colors-success-900) / <alpha-value>)",
        950: "rgb(var(--colors-success-950) / <alpha-value>)",
    },
    "gray-blue": {
        25: "rgb(var(--colors-gray-blue-25) / <alpha-value>)",
        50: "rgb(var(--colors-gray-blue-50) / <alpha-value>)",
        100: "rgb(var(--colors-gray-blue-100) / <alpha-value>)",
        200: "rgb(var(--colors-gray-blue-200) / <alpha-value>)",
        300: "rgb(var(--colors-gray-blue-300) / <alpha-value>)",
        400: "rgb(var(--colors-gray-blue-400) / <alpha-value>)",
        500: "rgb(var(--colors-gray-blue-500) / <alpha-value>)",
        600: "rgb(var(--colors-gray-blue-600) / <alpha-value>)",
        700: "rgb(var(--colors-gray-blue-700) / <alpha-value>)",
        800: "rgb(var(--colors-gray-blue-800) / <alpha-value>)",
        900: "rgb(var(--colors-gray-blue-900) / <alpha-value>)",
        950: "rgb(var(--colors-gray-blue-950) / <alpha-value>)",
    },
    "gray-cool": {
        25: "rgb(var(--colors-gray-cool-25) / <alpha-value>)",
        50: "rgb(var(--colors-gray-cool-50) / <alpha-value>)",
        100: "rgb(var(--colors-gray-cool-100) / <alpha-value>)",
        200: "rgb(var(--colors-gray-cool-200) / <alpha-value>)",
        300: "rgb(var(--colors-gray-cool-300) / <alpha-value>)",
        400: "rgb(var(--colors-gray-cool-400) / <alpha-value>)",
        500: "rgb(var(--colors-gray-cool-500) / <alpha-value>)",
        600: "rgb(var(--colors-gray-cool-600) / <alpha-value>)",
        700: "rgb(var(--colors-gray-cool-700) / <alpha-value>)",
        800: "rgb(var(--colors-gray-cool-800) / <alpha-value>)",
        900: "rgb(var(--colors-gray-cool-900) / <alpha-value>)",
        950: "rgb(var(--colors-gray-cool-950) / <alpha-value>)",
    },
    "gray-modern": {
        25: "rgb(var(--colors-gray-modern-25) / <alpha-value>)",
        50: "rgb(var(--colors-gray-modern-50) / <alpha-value>)",
        100: "rgb(var(--colors-gray-modern-100) / <alpha-value>)",
        200: "rgb(var(--colors-gray-modern-200) / <alpha-value>)",
        300: "rgb(var(--colors-gray-modern-300) / <alpha-value>)",
        400: "rgb(var(--colors-gray-modern-400) / <alpha-value>)",
        500: "rgb(var(--colors-gray-modern-500) / <alpha-value>)",
        600: "rgb(var(--colors-gray-modern-600) / <alpha-value>)",
        700: "rgb(var(--colors-gray-modern-700) / <alpha-value>)",
        800: "rgb(var(--colors-gray-modern-800) / <alpha-value>)",
        900: "rgb(var(--colors-gray-modern-900) / <alpha-value>)",
        950: "rgb(var(--colors-gray-modern-950) / <alpha-value>)",
    },
    "gray-neutral": {
        25: "rgb(var(--colors-gray-neutral-25) / <alpha-value>)",
        50: "rgb(var(--colors-gray-neutral-50) / <alpha-value>)",
        100: "rgb(var(--colors-gray-neutral-100) / <alpha-value>)",
        200: "rgb(var(--colors-gray-neutral-200) / <alpha-value>)",
        300: "rgb(var(--colors-gray-neutral-300) / <alpha-value>)",
        400: "rgb(var(--colors-gray-neutral-400) / <alpha-value>)",
        500: "rgb(var(--colors-gray-neutral-500) / <alpha-value>)",
        600: "rgb(var(--colors-gray-neutral-600) / <alpha-value>)",
        700: "rgb(var(--colors-gray-neutral-700) / <alpha-value>)",
        800: "rgb(var(--colors-gray-neutral-800) / <alpha-value>)",
        900: "rgb(var(--colors-gray-neutral-900) / <alpha-value>)",
        950: "rgb(var(--colors-gray-neutral-950) / <alpha-value>)",
    },
    "gray-iron": {
        25: "rgb(var(--colors-gray-iron-25) / <alpha-value>)",
        50: "rgb(var(--colors-gray-iron-50) / <alpha-value>)",
        100: "rgb(var(--colors-gray-iron-100) / <alpha-value>)",
        200: "rgb(var(--colors-gray-iron-200) / <alpha-value>)",
        300: "rgb(var(--colors-gray-iron-300) / <alpha-value>)",
        400: "rgb(var(--colors-gray-iron-400) / <alpha-value>)",
        500: "rgb(var(--colors-gray-iron-500) / <alpha-value>)",
        600: "rgb(var(--colors-gray-iron-600) / <alpha-value>)",
        700: "rgb(var(--colors-gray-iron-700) / <alpha-value>)",
        800: "rgb(var(--colors-gray-iron-800) / <alpha-value>)",
        900: "rgb(var(--colors-gray-iron-900) / <alpha-value>)",
        950: "rgb(var(--colors-gray-iron-950) / <alpha-value>)",
    },
    "gray-true": {
        25: "rgb(var(--colors-gray-true-25) / <alpha-value>)",
        50: "rgb(var(--colors-gray-true-50) / <alpha-value>)",
        100: "rgb(var(--colors-gray-true-100) / <alpha-value>)",
        200: "rgb(var(--colors-gray-true-200) / <alpha-value>)",
        300: "rgb(var(--colors-gray-true-300) / <alpha-value>)",
        400: "rgb(var(--colors-gray-true-400) / <alpha-value>)",
        500: "rgb(var(--colors-gray-true-500) / <alpha-value>)",
        600: "rgb(var(--colors-gray-true-600) / <alpha-value>)",
        700: "rgb(var(--colors-gray-true-700) / <alpha-value>)",
        800: "rgb(var(--colors-gray-true-800) / <alpha-value>)",
        900: "rgb(var(--colors-gray-true-900) / <alpha-value>)",
        950: "rgb(var(--colors-gray-true-950) / <alpha-value>)",
    },
    "gray-warm": {
        25: "rgb(var(--colors-gray-warm-25) / <alpha-value>)",
        50: "rgb(var(--colors-gray-warm-50) / <alpha-value>)",
        100: "rgb(var(--colors-gray-warm-100) / <alpha-value>)",
        200: "rgb(var(--colors-gray-warm-200) / <alpha-value>)",
        300: "rgb(var(--colors-gray-warm-300) / <alpha-value>)",
        400: "rgb(var(--colors-gray-warm-400) / <alpha-value>)",
        500: "rgb(var(--colors-gray-warm-500) / <alpha-value>)",
        600: "rgb(var(--colors-gray-warm-600) / <alpha-value>)",
        700: "rgb(var(--colors-gray-warm-700) / <alpha-value>)",
        800: "rgb(var(--colors-gray-warm-800) / <alpha-value>)",
        900: "rgb(var(--colors-gray-warm-900) / <alpha-value>)",
        950: "rgb(var(--colors-gray-warm-950) / <alpha-value>)",
    },
    moss: {
        25: "rgb(var(--colors-moss-25) / <alpha-value>)",
        50: "rgb(var(--colors-moss-50) / <alpha-value>)",
        100: "rgb(var(--colors-moss-100) / <alpha-value>)",
        200: "rgb(var(--colors-moss-200) / <alpha-value>)",
        300: "rgb(var(--colors-moss-300) / <alpha-value>)",
        400: "rgb(var(--colors-moss-400) / <alpha-value>)",
        500: "rgb(var(--colors-moss-500) / <alpha-value>)",
        600: "rgb(var(--colors-moss-600) / <alpha-value>)",
        700: "rgb(var(--colors-moss-700) / <alpha-value>)",
        800: "rgb(var(--colors-moss-800) / <alpha-value>)",
        900: "rgb(var(--colors-moss-900) / <alpha-value>)",
        950: "rgb(var(--colors-moss-950) / <alpha-value>)",
    },
    "green-light": {
        25: "rgb(var(--colors-green-light-25) / <alpha-value>)",
        50: "rgb(var(--colors-green-light-50) / <alpha-value>)",
        100: "rgb(var(--colors-green-light-100) / <alpha-value>)",
        200: "rgb(var(--colors-green-light-200) / <alpha-value>)",
        300: "rgb(var(--colors-green-light-300) / <alpha-value>)",
        400: "rgb(var(--colors-green-light-400) / <alpha-value>)",
        500: "rgb(var(--colors-green-light-500) / <alpha-value>)",
        600: "rgb(var(--colors-green-light-600) / <alpha-value>)",
        700: "rgb(var(--colors-green-light-700) / <alpha-value>)",
        800: "rgb(var(--colors-green-light-800) / <alpha-value>)",
        900: "rgb(var(--colors-green-light-900) / <alpha-value>)",
        950: "rgb(var(--colors-green-light-950) / <alpha-value>)",
    },
    green: {
        25: "rgb(var(--colors-green-25) / <alpha-value>)",
        50: "rgb(var(--colors-green-50) / <alpha-value>)",
        100: "rgb(var(--colors-green-100) / <alpha-value>)",
        200: "rgb(var(--colors-green-200) / <alpha-value>)",
        300: "rgb(var(--colors-green-300) / <alpha-value>)",
        400: "rgb(var(--colors-green-400) / <alpha-value>)",
        500: "rgb(var(--colors-green-500) / <alpha-value>)",
        600: "rgb(var(--colors-green-600) / <alpha-value>)",
        700: "rgb(var(--colors-green-700) / <alpha-value>)",
        800: "rgb(var(--colors-green-800) / <alpha-value>)",
        900: "rgb(var(--colors-green-900) / <alpha-value>)",
        950: "rgb(var(--colors-green-950) / <alpha-value>)",
    },
    teal: {
        25: "rgb(var(--colors-teal-25) / <alpha-value>)",
        50: "rgb(var(--colors-teal-50) / <alpha-value>)",
        100: "rgb(var(--colors-teal-100) / <alpha-value>)",
        200: "rgb(var(--colors-teal-200) / <alpha-value>)",
        300: "rgb(var(--colors-teal-300) / <alpha-value>)",
        400: "rgb(var(--colors-teal-400) / <alpha-value>)",
        500: "rgb(var(--colors-teal-500) / <alpha-value>)",
        600: "rgb(var(--colors-teal-600) / <alpha-value>)",
        700: "rgb(var(--colors-teal-700) / <alpha-value>)",
        800: "rgb(var(--colors-teal-800) / <alpha-value>)",
        900: "rgb(var(--colors-teal-900) / <alpha-value>)",
        950: "rgb(var(--colors-teal-950) / <alpha-value>)",
    },
    cyan: {
        25: "rgb(var(--colors-cyan-25) / <alpha-value>)",
        50: "rgb(var(--colors-cyan-50) / <alpha-value>)",
        100: "rgb(var(--colors-cyan-100) / <alpha-value>)",
        200: "rgb(var(--colors-cyan-200) / <alpha-value>)",
        300: "rgb(var(--colors-cyan-300) / <alpha-value>)",
        400: "rgb(var(--colors-cyan-400) / <alpha-value>)",
        500: "rgb(var(--colors-cyan-500) / <alpha-value>)",
        600: "rgb(var(--colors-cyan-600) / <alpha-value>)",
        700: "rgb(var(--colors-cyan-700) / <alpha-value>)",
        800: "rgb(var(--colors-cyan-800) / <alpha-value>)",
        900: "rgb(var(--colors-cyan-900) / <alpha-value>)",
        950: "rgb(var(--colors-cyan-950) / <alpha-value>)",
    },
    "blue-light": {
        25: "rgb(var(--colors-blue-light-25) / <alpha-value>)",
        50: "rgb(var(--colors-blue-light-50) / <alpha-value>)",
        100: "rgb(var(--colors-blue-light-100) / <alpha-value>)",
        200: "rgb(var(--colors-blue-light-200) / <alpha-value>)",
        300: "rgb(var(--colors-blue-light-300) / <alpha-value>)",
        400: "rgb(var(--colors-blue-light-400) / <alpha-value>)",
        500: "rgb(var(--colors-blue-light-500) / <alpha-value>)",
        600: "rgb(var(--colors-blue-light-600) / <alpha-value>)",
        700: "rgb(var(--colors-blue-light-700) / <alpha-value>)",
        800: "rgb(var(--colors-blue-light-800) / <alpha-value>)",
        900: "rgb(var(--colors-blue-light-900) / <alpha-value>)",
        950: "rgb(var(--colors-blue-light-950) / <alpha-value>)",
    },
    blue: {
        25: "rgb(var(--colors-blue-25) / <alpha-value>)",
        50: "rgb(var(--colors-blue-50) / <alpha-value>)",
        100: "rgb(var(--colors-blue-100) / <alpha-value>)",
        200: "rgb(var(--colors-blue-200) / <alpha-value>)",
        300: "rgb(var(--colors-blue-300) / <alpha-value>)",
        400: "rgb(var(--colors-blue-400) / <alpha-value>)",
        500: "rgb(var(--colors-blue-500) / <alpha-value>)",
        600: "rgb(var(--colors-blue-600) / <alpha-value>)",
        700: "rgb(var(--colors-blue-700) / <alpha-value>)",
        800: "rgb(var(--colors-blue-800) / <alpha-value>)",
        900: "rgb(var(--colors-blue-900) / <alpha-value>)",
        950: "rgb(var(--colors-blue-950) / <alpha-value>)",
    },
    "blue-dark": {
        25: "rgb(var(--colors-blue-dark-25) / <alpha-value>)",
        50: "rgb(var(--colors-blue-dark-50) / <alpha-value>)",
        100: "rgb(var(--colors-blue-dark-100) / <alpha-value>)",
        200: "rgb(var(--colors-blue-dark-200) / <alpha-value>)",
        300: "rgb(var(--colors-blue-dark-300) / <alpha-value>)",
        400: "rgb(var(--colors-blue-dark-400) / <alpha-value>)",
        500: "rgb(var(--colors-blue-dark-500) / <alpha-value>)",
        600: "rgb(var(--colors-blue-dark-600) / <alpha-value>)",
        700: "rgb(var(--colors-blue-dark-700) / <alpha-value>)",
        800: "rgb(var(--colors-blue-dark-800) / <alpha-value>)",
        900: "rgb(var(--colors-blue-dark-900) / <alpha-value>)",
        950: "rgb(var(--colors-blue-dark-950) / <alpha-value>)",
    },
    indigo: {
        25: "rgb(var(--colors-indigo-25) / <alpha-value>)",
        50: "rgb(var(--colors-indigo-50) / <alpha-value>)",
        100: "rgb(var(--colors-indigo-100) / <alpha-value>)",
        200: "rgb(var(--colors-indigo-200) / <alpha-value>)",
        300: "rgb(var(--colors-indigo-300) / <alpha-value>)",
        400: "rgb(var(--colors-indigo-400) / <alpha-value>)",
        500: "rgb(var(--colors-indigo-500) / <alpha-value>)",
        600: "rgb(var(--colors-indigo-600) / <alpha-value>)",
        700: "rgb(var(--colors-indigo-700) / <alpha-value>)",
        800: "rgb(var(--colors-indigo-800) / <alpha-value>)",
        900: "rgb(var(--colors-indigo-900) / <alpha-value>)",
        950: "rgb(var(--colors-indigo-950) / <alpha-value>)",
    },
    violet: {
        25: "rgb(var(--colors-violet-25) / <alpha-value>)",
        50: "rgb(var(--colors-violet-50) / <alpha-value>)",
        100: "rgb(var(--colors-violet-100) / <alpha-value>)",
        200: "rgb(var(--colors-violet-200) / <alpha-value>)",
        300: "rgb(var(--colors-violet-300) / <alpha-value>)",
        400: "rgb(var(--colors-violet-400) / <alpha-value>)",
        500: "rgb(var(--colors-violet-500) / <alpha-value>)",
        600: "rgb(var(--colors-violet-600) / <alpha-value>)",
        700: "rgb(var(--colors-violet-700) / <alpha-value>)",
        800: "rgb(var(--colors-violet-800) / <alpha-value>)",
        900: "rgb(var(--colors-violet-900) / <alpha-value>)",
        950: "rgb(var(--colors-violet-950) / <alpha-value>)",
    },
    purple: {
        25: "rgb(var(--colors-purple-25) / <alpha-value>)",
        50: "rgb(var(--colors-purple-50) / <alpha-value>)",
        100: "rgb(var(--colors-purple-100) / <alpha-value>)",
        200: "rgb(var(--colors-purple-200) / <alpha-value>)",
        300: "rgb(var(--colors-purple-300) / <alpha-value>)",
        400: "rgb(var(--colors-purple-400) / <alpha-value>)",
        500: "rgb(var(--colors-purple-500) / <alpha-value>)",
        600: "rgb(var(--colors-purple-600) / <alpha-value>)",
        700: "rgb(var(--colors-purple-700) / <alpha-value>)",
        800: "rgb(var(--colors-purple-800) / <alpha-value>)",
        900: "rgb(var(--colors-purple-900) / <alpha-value>)",
        950: "rgb(var(--colors-purple-950) / <alpha-value>)",
    },
    fuchsia: {
        25: "rgb(var(--colors-fuchsia-25) / <alpha-value>)",
        50: "rgb(var(--colors-fuchsia-50) / <alpha-value>)",
        100: "rgb(var(--colors-fuchsia-100) / <alpha-value>)",
        200: "rgb(var(--colors-fuchsia-200) / <alpha-value>)",
        300: "rgb(var(--colors-fuchsia-300) / <alpha-value>)",
        400: "rgb(var(--colors-fuchsia-400) / <alpha-value>)",
        500: "rgb(var(--colors-fuchsia-500) / <alpha-value>)",
        600: "rgb(var(--colors-fuchsia-600) / <alpha-value>)",
        700: "rgb(var(--colors-fuchsia-700) / <alpha-value>)",
        800: "rgb(var(--colors-fuchsia-800) / <alpha-value>)",
        900: "rgb(var(--colors-fuchsia-900) / <alpha-value>)",
        950: "rgb(var(--colors-fuchsia-950) / <alpha-value>)",
    },
    pink: {
        25: "rgb(var(--colors-pink-25) / <alpha-value>)",
        50: "rgb(var(--colors-pink-50) / <alpha-value>)",
        100: "rgb(var(--colors-pink-100) / <alpha-value>)",
        200: "rgb(var(--colors-pink-200) / <alpha-value>)",
        300: "rgb(var(--colors-pink-300) / <alpha-value>)",
        400: "rgb(var(--colors-pink-400) / <alpha-value>)",
        500: "rgb(var(--colors-pink-500) / <alpha-value>)",
        600: "rgb(var(--colors-pink-600) / <alpha-value>)",
        700: "rgb(var(--colors-pink-700) / <alpha-value>)",
        800: "rgb(var(--colors-pink-800) / <alpha-value>)",
        900: "rgb(var(--colors-pink-900) / <alpha-value>)",
        950: "rgb(var(--colors-pink-950) / <alpha-value>)",
    },
    rose: {
        25: "rgb(var(--colors-rose-25) / <alpha-value>)",
        50: "rgb(var(--colors-rose-50) / <alpha-value>)",
        100: "rgb(var(--colors-rose-100) / <alpha-value>)",
        200: "rgb(var(--colors-rose-200) / <alpha-value>)",
        300: "rgb(var(--colors-rose-300) / <alpha-value>)",
        400: "rgb(var(--colors-rose-400) / <alpha-value>)",
        500: "rgb(var(--colors-rose-500) / <alpha-value>)",
        600: "rgb(var(--colors-rose-600) / <alpha-value>)",
        700: "rgb(var(--colors-rose-700) / <alpha-value>)",
        800: "rgb(var(--colors-rose-800) / <alpha-value>)",
        900: "rgb(var(--colors-rose-900) / <alpha-value>)",
        950: "rgb(var(--colors-rose-950) / <alpha-value>)",
    },
    "orange-dark": {
        25: "rgb(var(--colors-orange-dark-25) / <alpha-value>)",
        50: "rgb(var(--colors-orange-dark-50) / <alpha-value>)",
        100: "rgb(var(--colors-orange-dark-100) / <alpha-value>)",
        200: "rgb(var(--colors-orange-dark-200) / <alpha-value>)",
        300: "rgb(var(--colors-orange-dark-300) / <alpha-value>)",
        400: "rgb(var(--colors-orange-dark-400) / <alpha-value>)",
        500: "rgb(var(--colors-orange-dark-500) / <alpha-value>)",
        600: "rgb(var(--colors-orange-dark-600) / <alpha-value>)",
        700: "rgb(var(--colors-orange-dark-700) / <alpha-value>)",
        800: "rgb(var(--colors-orange-dark-800) / <alpha-value>)",
        900: "rgb(var(--colors-orange-dark-900) / <alpha-value>)",
        950: "rgb(var(--colors-orange-dark-950) / <alpha-value>)",
    },
    orange: {
        25: "rgb(var(--colors-orange-25) / <alpha-value>)",
        50: "rgb(var(--colors-orange-50) / <alpha-value>)",
        100: "rgb(var(--colors-orange-100) / <alpha-value>)",
        200: "rgb(var(--colors-orange-200) / <alpha-value>)",
        300: "rgb(var(--colors-orange-300) / <alpha-value>)",
        400: "rgb(var(--colors-orange-400) / <alpha-value>)",
        500: "rgb(var(--colors-orange-500) / <alpha-value>)",
        600: "rgb(var(--colors-orange-600) / <alpha-value>)",
        700: "rgb(var(--colors-orange-700) / <alpha-value>)",
        800: "rgb(var(--colors-orange-800) / <alpha-value>)",
        900: "rgb(var(--colors-orange-900) / <alpha-value>)",
        950: "rgb(var(--colors-orange-950) / <alpha-value>)",
    },
    yellow: {
        25: "rgb(var(--colors-yellow-25) / <alpha-value>)",
        50: "rgb(var(--colors-yellow-50) / <alpha-value>)",
        100: "rgb(var(--colors-yellow-100) / <alpha-value>)",
        200: "rgb(var(--colors-yellow-200) / <alpha-value>)",
        300: "rgb(var(--colors-yellow-300) / <alpha-value>)",
        400: "rgb(var(--colors-yellow-400) / <alpha-value>)",
        500: "rgb(var(--colors-yellow-500) / <alpha-value>)",
        600: "rgb(var(--colors-yellow-600) / <alpha-value>)",
        700: "rgb(var(--colors-yellow-700) / <alpha-value>)",
        800: "rgb(var(--colors-yellow-800) / <alpha-value>)",
        900: "rgb(var(--colors-yellow-900) / <alpha-value>)",
        950: "rgb(var(--colors-yellow-950) / <alpha-value>)",
    },
};
