import { colors } from "./colors";

export const themeColors = {
    backgroundColor: {
        quaternary: "rgb(var(--colors-bg-quaternary) / <alpha-value>)",
        "brand-solid": "rgb(var(--colors-bg-brand-solid) / <alpha-value>)",
        disabled: "rgb(var(--colors-bg-disabled) / <alpha-value>)",
        primary: "rgb(var(--colors-bg-primary) / <alpha-value>)",
        "primary-solid": "rgb(var(--colors-bg-primary-solid) / <alpha-value>)",
        primary_alt: "rgb(var(--colors-bg-primary_alt) / <alpha-value>)",
        primary_hover: "rgb(var(--colors-bg-primary_hover) / <alpha-value>)",
        secondary: {
            DEFAULT: "rgb(var(--colors-bg-secondary) / <alpha-value>)",
            solid: "rgb(var(--colors-bg-secondary-solid) / <alpha-value>)",
        },
        secondary_alt: "rgb(var(--colors-bg-secondary_alt) / <alpha-value>)",
        secondary_hover: "rgb(var(--colors-bg-secondary_hover) / <alpha-value>)",
        secondary_subtle: "rgb(var(--colors-bg-secondary_subtle) / <alpha-value>)",
        tertiary: "rgb(var(--colors-bg-tertiary) / <alpha-value>)",
        active: "rgb(var(--colors-bg-active) / <alpha-value>)",
        disabled_subtle: "rgb(var(--colors-bg-disabled_subtle) / <alpha-value>)",
        overlay: "rgb(var(--colors-bg-overlay) / <alpha-value>)",
        brand: {
            primary: "rgb(var(--colors-bg-brand-primary) / <alpha-value>)",
            primary_alt: "rgb(var(--colors-bg-brand-primary_alt) / <alpha-value>)",
            secondary: "rgb(var(--colors-bg-brand-secondary) / <alpha-value>)",
            solid: "rgb(var(--colors-bg-brand-solid) / <alpha-value>)",
            solid_hover: "rgb(var(--colors-bg-brand-solid_hover) / <alpha-value>)",
            section: "rgb(var(--colors-bg-brand-section) / <alpha-value>)",
            section_subtle: "rgb(var(--colors-bg-brand-section_subtle) / <alpha-value>)",
        },
        error: {
            primary: "rgb(var(--colors-bg-error-primary) / <alpha-value>)",
            secondary: "rgb(var(--colors-bg-error-secondary) / <alpha-value>)",
            solid: "rgb(var(--colors-bg-error-solid) / <alpha-value>)",
        },
        warning: {
            primary: "rgb(var(--colors-bg-warning-primary) / <alpha-value>)",
            secondary: "rgb(var(--colors-bg-warning-secondary) / <alpha-value>)",
            solid: "rgb(var(--colors-bg-warning-solid) / <alpha-value>)",
        },
        success: {
            primary: "rgb(var(--colors-bg-success-primary) / <alpha-value>)",
            secondary: "rgb(var(--colors-bg-success-secondary) / <alpha-value>)",
            solid: "rgb(var(--colors-bg-success-solid) / <alpha-value>)",
        },
        "border-brand": "rgb(var(--colors-border-brand) / <alpha-value>)",
        "border-tertiary": "rgb(var(--colors-border-tertiary) / <alpha-value>)",
        "border-brand_alt": "rgb(var(--colors-border-brand_alt) / <alpha-value>)",
        "border-brand_alt-REMOVED": "rgb(var(--colors-border-brand_alt-REMOVED) / <alpha-value>)",
    },

    textColor: {
        primary: {
            DEFAULT: "rgb(var(--colors-text-primary) / <alpha-value>)",
        },
        primary_on: {
            brand: "rgb(var(--colors-text-primary_on-brand) / <alpha-value>)",
        },
        secondary: "rgb(var(--colors-text-secondary) / <alpha-value>)",
        secondary_hover: "rgb(var(--colors-text-secondary_hover) / <alpha-value>)",
        secondary_on: {
            brand: "rgb(var(--colors-text-secondary_on-brand) / <alpha-value>)",
        },
        tertiary: "rgb(var(--colors-text-tertiary) / <alpha-value>)",
        tertiary_hover: "rgb(var(--colors-text-tertiary_hover) / <alpha-value>)",
        tertiary_on: {
            brand: "rgb(var(--colors-text-tertiary_on-brand) / <alpha-value>)",
        },
        quaternary: "rgb(var(--colors-text-quaternary) / <alpha-value>)",
        quaternary_on: {
            brand: "rgb(var(--colors-text-quaternary_on-brand) / <alpha-value>)",
        },
        disabled: "rgb(var(--colors-text-disabled) / <alpha-value>)",
        placeholder: "rgb(var(--colors-text-placeholder) / <alpha-value>)",
        placeholder_subtle: "rgb(var(--colors-text-placeholder_subtle) / <alpha-value>)",
        brand: {
            primary: "rgb(var(--colors-text-brand-primary) / <alpha-value>)",
            secondary: "rgb(var(--colors-text-brand-secondary) / <alpha-value>)",
            tertiary: "rgb(var(--colors-text-brand-tertiary) / <alpha-value>)",
            tertiary_alt: "rgb(var(--colors-text-brand-tertiary_alt) / <alpha-value>)",
        },
        error: {
            primary: "rgb(var(--colors-text-error-primary) / <alpha-value>)",
        },
        warning: {
            primary: "rgb(var(--colors-text-warning-primary) / <alpha-value>)",
        },
        success: {
            primary: "rgb(var(--colors-text-success-primary) / <alpha-value>)",
        },
        tooltip: {
            "supporting-text": "rgb(var(--colors-tooltip-supporting-text) / <alpha-value>)",
        },
    },
    borderColor: {
        primary: {
            DEFAULT: "rgb(var(--colors-border-primary) / <alpha-value>)",
        },
        secondary: "rgb(var(--colors-border-secondary) / <alpha-value>)",
        tertiary: "rgb(var(--colors-border-tertiary) / <alpha-value>)",
        disabled: "rgb(var(--colors-border-disabled) / <alpha-value>)",
        brand: {
            DEFAULT: "rgb(var(--colors-border-brand) / <alpha-value>)",
            solid: "rgb(var(--colors-bg-brand-solid) / <alpha-value>)",
            solid_hover: "rgb(var(--colors-bg-brand-solid_hover) / <alpha-value>)",
        },
        error: {
            DEFAULT: "rgb(var(--colors-border-error) / <alpha-value>)",
        },
        disabled_subtle: "rgb(var(--colors-border-disabled_subtle) / <alpha-value>)",
        brand_alt: "rgb(var(--colors-border-brand_alt) / <alpha-value>)",
        error_subtle: "rgb(var(--colors-border-error_subtle) / <alpha-value>)",
        "brand_alt-REMOVED": "rgb(var(--colors-border-brand_alt-REMOVED) / <alpha-value>)",
    },
    ringColor: {
        bg: {
            brand: {
                solid: "rgb(var(--colors-bg-brand-solid) / <alpha-value>)",
            },
        },
        border: {
            primary: "rgb(var(--colors-border-primary) / <alpha-value>)",
            secondary: "rgb(var(--colors-border-secondary) / <alpha-value>)",
            tertiary: "rgb(var(--colors-border-tertiary) / <alpha-value>)",
            disabled: "rgb(var(--colors-border-disabled) / <alpha-value>)",
            brand: "rgb(var(--colors-border-brand) / <alpha-value>)",
            error: "rgb(var(--colors-border-error) / <alpha-value>)",
            disabled_subtle: "rgb(var(--colors-border-disabled_subtle) / <alpha-value>)",
            brand_alt: "rgb(var(--colors-border-brand_alt) / <alpha-value>)",
            error_subtle: "rgb(var(--colors-border-error_subtle) / <alpha-value>)",
            "brand_alt-REMOVED": "rgb(var(--colors-border-brand_alt-REMOVED) / <alpha-value>)",
        },
        toggle: {
            border: "rgb(var(--colors-toggle-border) / <alpha-value>)",
            border_pressed: "rgb(var(--colors-toggle-slim-border_pressed) / <alpha-value>)",
            "border_pressed-hover": "rgb(var(--colors-toggle-slim-border_pressed-hover) / <alpha-value>)",
        },
    },
    outlineColor: {
        brand: {
            DEFAULT: "rgb(var(--colors-border-brand) / <alpha-value>)",
        },
        primary: {
            DEFAULT: "rgb(var(--colors-border-primary) / <alpha-value>)",
        },
        secondary: {
            DEFAULT: "rgb(var(--colors-border-secondary) / <alpha-value>)",
        },
        error: {
            DEFAULT: "rgb(var(--colors-border-error) / <alpha-value>)",
        },
    },
    colors: {
        ...colors,

        // tertiary: "rgb(var(--colors-tertiary) / <alpha-value>)",
        // overlay: "rgb(var(--colors-overlay) / <alpha-value>)",
        button: {
            primary: {
                fg: "rgb(var(--colors-button-primary-fg) / <alpha-value>)",
                fg_hover: "rgb(var(--colors-button-primary-fg_hover) / <alpha-value>)",
                bg: "rgb(var(--colors-button-primary-bg) / <alpha-value>)",
                bg_hover: "rgb(var(--colors-button-primary-bg_hover) / <alpha-value>)",
                error: {
                    fg: "rgb(var(--colors-button-primary-error-fg) / <alpha-value>)",
                    fg_hover: "rgb(var(--colors-button-primary-error-fg_hover) / <alpha-value>)",
                    bg: "rgb(var(--colors-button-primary-error-bg) / <alpha-value>)",
                    bg_hover: "rgb(var(--colors-button-primary-error-bg_hover) / <alpha-value>)",
                },
            },
            secondary: {
                fg: "rgb(var(--colors-button-secondary-fg) / <alpha-value>)",
                fg_hover: "rgb(var(--colors-button-secondary-fg_hover) / <alpha-value>)",
                bg: "rgb(var(--colors-button-secondary-bg) / <alpha-value>)",
                bg_hover: "rgb(var(--colors-button-secondary-bg_hover) / <alpha-value>)",
                border: "rgb(var(--colors-button-secondary-border) / <alpha-value>)",
                border_hover: "rgb(var(--colors-button-secondary-border_hover) / <alpha-value>)",
                color: {
                    fg: "rgb(var(--colors-button-secondary-color-fg) / <alpha-value>)",
                    fg_hover: "rgb(var(--colors-button-secondary-color-fg_hover) / <alpha-value>)",
                    bg: "rgb(var(--colors-button-secondary-color-bg) / <alpha-value>)",
                    bg_hover: "rgb(var(--colors-button-secondary-color-bg_hover) / <alpha-value>)",
                    border: "rgb(var(--colors-button-secondary-color-border) / <alpha-value>)",
                    border_hover: "rgb(var(--colors-button-secondary-color-border_hover) / <alpha-value>)",
                },
                error: {
                    fg: "rgb(var(--colors-button-secondary-error-fg) / <alpha-value>)",
                    fg_hover: "rgb(var(--colors-button-secondary-error-fg_hover) / <alpha-value>)",
                    bg: "rgb(var(--colors-button-secondary-error-bg) / <alpha-value>)",
                    bg_hover: "rgb(var(--colors-button-secondary-error-bg_hover) / <alpha-value>)",
                    border: "rgb(var(--colors-button-secondary-error-border) / <alpha-value>)",
                    border_hover: "rgb(var(--colors-button-secondary-error-border_hover) / <alpha-value>)",
                },
            },
            tertiary: {
                fg: "rgb(var(--colors-button-tertiary-fg) / <alpha-value>)",
                fg_hover: "rgb(var(--colors-button-tertiary-fg_hover) / <alpha-value>)",
                bg_hover: "rgb(var(--colors-button-tertiary-bg_hover) / <alpha-value>)",
                color: {
                    fg: "rgb(var(--colors-button-tertiary-color-fg) / <alpha-value>)",
                    fg_hover: "rgb(var(--colors-button-tertiary-color-fg_hover) / <alpha-value>)",
                    bg_hover: "rgb(var(--colors-button-tertiary-color-bg_hover) / <alpha-value>)",
                },
                error: {
                    fg: "rgb(var(--colors-button-tertiary-error-fg) / <alpha-value>)",
                    fg_hover: "rgb(var(--colors-button-tertiary-error-fg_hover) / <alpha-value>)",
                    bg_hover: "rgb(var(--colors-button-tertiary-error-bg_hover) / <alpha-value>)",
                },
            },
        },
        bg: {
            primary: "rgb(var(--colors-bg-primary) / <alpha-value>)",
            "primary-solid": "rgb(var(--colors-bg-primary-solid) / <alpha-value>)",
            secondary: "rgb(var(--colors-bg-secondary) / <alpha-value>)",
            tertiary: "rgb(var(--colors-bg-tertiary) / <alpha-value>)",
            quaternary: "rgb(var(--colors-bg-quaternary) / <alpha-value>)",
            success: {
                solid: "rgb(var(--colors-bg-success-solid) / <alpha-value>)",
            },
        },
        fg: {
            primary: "rgb(var(--colors-fg-primary) / <alpha-value>)",
            secondary: "rgb(var(--colors-fg-secondary) / <alpha-value>)",
            secondary_hover: "rgb(var(--colors-fg-secondary_hover) / <alpha-value>)",
            tertiary: "rgb(var(--colors-fg-tertiary) / <alpha-value>)",
            tertiary_hover: "rgb(var(--colors-fg-tertiary_hover) / <alpha-value>)",
            quaternary: "rgb(var(--colors-fg-quaternary) / <alpha-value>)",
            quaternary_hover: "rgb(var(--colors-fg-quaternary_hover) / <alpha-value>)",
            quinary: "rgb(var(--colors-fg-quinary) / <alpha-value>)",
            quinary_hover: "rgb(var(--colors-fg-quinary_hover) / <alpha-value>)",
            senary: "rgb(var(--colors-fg-senary) / <alpha-value>)",
            white: "rgb(var(--colors-fg-white) / <alpha-value>)",
            disabled: "rgb(var(--colors-fg-disabled) / <alpha-value>)",
            disabled_subtle: "rgb(var(--colors-fg-disabled_subtle) / <alpha-value>)",
            brand: {
                primary: "rgb(var(--colors-fg-brand-primary) / <alpha-value>)",
                primary_alt: "rgb(var(--colors-fg-brand-primary_alt) / <alpha-value>)",
                secondary: "rgb(var(--colors-fg-brand-secondary) / <alpha-value>)",
            },
            error: {
                primary: "rgb(var(--colors-fg-error-primary) / <alpha-value>)",
                secondary: "rgb(var(--colors-fg-error-secondary) / <alpha-value>)",
            },
            warning: {
                primary: "rgb(var(--colors-fg-warning-primary) / <alpha-value>)",
                secondary: "rgb(var(--colors-fg-warning-secondary) / <alpha-value>)",
            },
            success: {
                primary: "rgb(var(--colors-fg-success-primary) / <alpha-value>)",
                secondary: "rgb(var(--colors-fg-success-secondary) / <alpha-value>)",
            },
        },
        focus: {
            ring: {
                DEFAULT: "rgb(var(--colors-focus-ring) / <alpha-value>)",
                error: "rgb(var(--colors-focus-ring-error) / <alpha-value>)",
            },
        },
        border: {
            secondary: "rgb(var(--colors-border-secondary) / <alpha-value>)",
        },
        slider: {
            handle: {
                bg: "rgb(var(--colors-slider-handle-bg) / <alpha-value>)",
                border: "rgb(var(--colors-slider-handle-border) / <alpha-value>)",
            },
        },
        utility: {
            gray: {
                50: "rgb(var(--colors-utility-gray-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-gray-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-gray-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-gray-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-gray-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-gray-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-gray-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-gray-700) / <alpha-value>)",
                800: "rgb(var(--colors-utility-gray-800) / <alpha-value>)",
                900: "rgb(var(--colors-utility-gray-900) / <alpha-value>)",
                blue: {
                    50: "rgb(var(--colors-utility-gray-blue-50) / <alpha-value>)",
                    100: "rgb(var(--colors-utility-gray-blue-100) / <alpha-value>)",
                    200: "rgb(var(--colors-utility-gray-blue-200) / <alpha-value>)",
                    300: "rgb(var(--colors-utility-gray-blue-300) / <alpha-value>)",
                    400: "rgb(var(--colors-utility-gray-blue-400) / <alpha-value>)",
                    500: "rgb(var(--colors-utility-gray-blue-500) / <alpha-value>)",
                    600: "rgb(var(--colors-utility-gray-blue-600) / <alpha-value>)",
                    700: "rgb(var(--colors-utility-gray-blue-700) / <alpha-value>)",
                },
            },
            brand: {
                50: "rgb(var(--colors-utility-brand-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-brand-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-brand-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-brand-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-brand-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-brand-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-brand-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-brand-700) / <alpha-value>)",
                800: "rgb(var(--colors-utility-brand-800) / <alpha-value>)",
                900: "rgb(var(--colors-utility-brand-900) / <alpha-value>)",
                "50_alt": "rgb(var(--colors-utility-brand-50_alt) / <alpha-value>)",
                "100_alt": "rgb(var(--colors-utility-brand-100_alt) / <alpha-value>)",
                "200_alt": "rgb(var(--colors-utility-brand-200_alt) / <alpha-value>)",
                "300_alt": "rgb(var(--colors-utility-brand-300_alt) / <alpha-value>)",
                "400_alt": "rgb(var(--colors-utility-brand-400_alt) / <alpha-value>)",
                "500_alt": "rgb(var(--colors-utility-brand-500_alt) / <alpha-value>)",
                "600_alt": "rgb(var(--colors-utility-brand-600_alt) / <alpha-value>)",
                "700_alt": "rgb(var(--colors-utility-brand-700_alt) / <alpha-value>)",
                "800_alt": "rgb(var(--colors-utility-brand-800_alt) / <alpha-value>)",
                "900_alt": "rgb(var(--colors-utility-brand-900_alt) / <alpha-value>)",
            },
            error: {
                50: "rgb(var(--colors-utility-error-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-error-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-error-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-error-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-error-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-error-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-error-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-error-700) / <alpha-value>)",
            },
            warning: {
                50: "rgb(var(--colors-utility-warning-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-warning-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-warning-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-warning-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-warning-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-warning-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-warning-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-warning-700) / <alpha-value>)",
            },
            success: {
                50: "rgb(var(--colors-utility-success-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-success-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-success-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-success-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-success-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-success-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-success-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-success-700) / <alpha-value>)",
            },
            blue: {
                50: "rgb(var(--colors-utility-blue-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-blue-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-blue-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-blue-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-blue-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-blue-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-blue-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-blue-700) / <alpha-value>)",
                light: {
                    50: "rgb(var(--colors-utility-blue-light-50) / <alpha-value>)",
                    100: "rgb(var(--colors-utility-blue-light-100) / <alpha-value>)",
                    200: "rgb(var(--colors-utility-blue-light-200) / <alpha-value>)",
                    300: "rgb(var(--colors-utility-blue-light-300) / <alpha-value>)",
                    400: "rgb(var(--colors-utility-blue-light-400) / <alpha-value>)",
                    500: "rgb(var(--colors-utility-blue-light-500) / <alpha-value>)",
                    600: "rgb(var(--colors-utility-blue-light-600) / <alpha-value>)",
                    700: "rgb(var(--colors-utility-blue-light-700) / <alpha-value>)",
                },
                dark: {
                    50: "rgb(var(--colors-utility-blue-dark-50) / <alpha-value>)",
                    100: "rgb(var(--colors-utility-blue-dark-100) / <alpha-value>)",
                    200: "rgb(var(--colors-utility-blue-dark-200) / <alpha-value>)",
                    300: "rgb(var(--colors-utility-blue-dark-300) / <alpha-value>)",
                    400: "rgb(var(--colors-utility-blue-dark-400) / <alpha-value>)",
                    500: "rgb(var(--colors-utility-blue-dark-500) / <alpha-value>)",
                    600: "rgb(var(--colors-utility-blue-dark-600) / <alpha-value>)",
                    700: "rgb(var(--colors-utility-blue-dark-700) / <alpha-value>)",
                },
            },
            green: {
                50: "rgb(var(--colors-utility-green-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-green-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-green-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-green-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-green-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-green-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-green-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-green-700) / <alpha-value>)",
            },
            yellow: {
                50: "rgb(var(--colors-utility-yellow-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-yellow-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-yellow-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-yellow-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-yellow-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-yellow-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-yellow-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-yellow-700) / <alpha-value>)",
            },
            indigo: {
                50: "rgb(var(--colors-utility-indigo-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-indigo-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-indigo-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-indigo-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-indigo-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-indigo-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-indigo-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-indigo-700) / <alpha-value>)",
            },
            purple: {
                50: "rgb(var(--colors-utility-purple-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-purple-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-purple-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-purple-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-purple-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-purple-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-purple-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-purple-700) / <alpha-value>)",
            },
            fuchsia: {
                50: "rgb(var(--colors-utility-fuchsia-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-fuchsia-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-fuchsia-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-fuchsia-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-fuchsia-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-fuchsia-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-fuchsia-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-fuchsia-700) / <alpha-value>)",
            },
            pink: {
                50: "rgb(var(--colors-utility-pink-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-pink-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-pink-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-pink-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-pink-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-pink-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-pink-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-pink-700) / <alpha-value>)",
            },
            orange: {
                50: "rgb(var(--colors-utility-orange-50) / <alpha-value>)",
                100: "rgb(var(--colors-utility-orange-100) / <alpha-value>)",
                200: "rgb(var(--colors-utility-orange-200) / <alpha-value>)",
                300: "rgb(var(--colors-utility-orange-300) / <alpha-value>)",
                400: "rgb(var(--colors-utility-orange-400) / <alpha-value>)",
                500: "rgb(var(--colors-utility-orange-500) / <alpha-value>)",
                600: "rgb(var(--colors-utility-orange-600) / <alpha-value>)",
                700: "rgb(var(--colors-utility-orange-700) / <alpha-value>)",
                dark: {
                    50: "rgb(var(--colors-utility-orange-dark-50) / <alpha-value>)",
                    100: "rgb(var(--colors-utility-orange-dark-100) / <alpha-value>)",
                    200: "rgb(var(--colors-utility-orange-dark-200) / <alpha-value>)",
                    300: "rgb(var(--colors-utility-orange-dark-300) / <alpha-value>)",
                    400: "rgb(var(--colors-utility-orange-dark-400) / <alpha-value>)",
                    500: "rgb(var(--colors-utility-orange-dark-500) / <alpha-value>)",
                    600: "rgb(var(--colors-utility-orange-dark-600) / <alpha-value>)",
                    700: "rgb(var(--colors-utility-orange-dark-700) / <alpha-value>)",
                },
            },
        },
        "app-store-badge": {
            border: "rgb(var(--colors-app-store-badge-border) / <alpha-value>)",
        },
        "nav-item": {
            button: {
                icon: {
                    fg: "rgb(var(--colors-nav-item-button-icon-fg) / <alpha-value>)",
                    fg_active: "rgb(var(--colors-nav-item-button-icon-fg_active) / <alpha-value>)",
                },
            },
            icon: {
                fg: "rgb(var(--colors-nav-item-icon-fg) / <alpha-value>)",
                fg_active: "rgb(var(--colors-nav-item-icon-fg_active) / <alpha-value>)",
            },
        },
        avatar: {
            bg: "rgb(var(--colors-avatar-bg) / <alpha-value>)",
            "profile-photo-border": "rgb(var(--colors-avatar-profile-photo-border) / <alpha-value>)",
            "contrast-border": "rgb(var(--colors-avatar-contrast-border))",
            "styles-bg-neutral": "rgb(var(--colors-avatar-styles-bg-neutral) / <alpha-value>)",
        },
        breadcrumb: {
            fg: "rgb(var(--colors-breadcrumb-fg) / <alpha-value>)",
            fg_hover: "rgb(var(--colors-breadcrumb-fg_hover) / <alpha-value>)",
            bg_hover: "rgb(var(--colors-breadcrumb-bg_hover) / <alpha-value>)",
            brand: {
                fg_hover: "rgb(var(--colors-breadcrumb-brand-fg_hover) / <alpha-value>)",
                bg_hover: "rgb(var(--colors-breadcrumb-brand-bg_hover) / <alpha-value>)",
                icon: {
                    fg_hover: "rgb(var(--colors-breadcrumb-brand-icon-fg_hover) / <alpha-value>)",
                },
            },
            icon: {
                fg: "rgb(var(--colors-breadcrumb-icon-fg) / <alpha-value>)",
                fg_hover: "rgb(var(--colors-breadcrumb-icon-fg_hover) / <alpha-value>)",
            },
        },
        footer: {
            button: {
                fg: "rgb(var(--colors-footer-button-fg) / <alpha-value>)",
                fg_hover: "rgb(var(--colors-footer-button-fg_hover) / <alpha-value>)",
            },
            badge: {
                fg: "rgb(var(--colors-footer-badge-fg) / <alpha-value>)",
                bg: "rgb(var(--colors-footer-badge-bg) / <alpha-value>)",
                border: "rgb(var(--colors-footer-badge-border) / <alpha-value>)",
            },
        },
        header: {
            abstract: {
                50: {
                    bg: "rgb(var(--colors-header-abstract-50-bg) / <alpha-value>)",
                },
                100: {
                    bg: "rgb(var(--colors-header-abstract-100-bg) / <alpha-value>)",
                },
                200: {
                    bg: "rgb(var(--colors-header-abstract-200-bg) / <alpha-value>)",
                },
                300: {
                    bg: "rgb(var(--colors-header-abstract-300-bg) / <alpha-value>)",
                },
            },
        },
        icon: {
            fg: {
                brand: "rgb(var(--colors-icon-fg-brand) / <alpha-value>)",
                brand_on: {
                    brand: "rgb(var(--colors-icon-fg-brand_on-brand) / <alpha-value>)",
                },
            },
        },
        "featured-icon": {
            light: {
                fg: {
                    brand: "rgb(var(--colors-featured-icon-light-fg-brand) / <alpha-value>)",
                    gray: "rgb(var(--colors-featured-icon-light-fg-gray) / <alpha-value>)",
                    error: "rgb(var(--colors-featured-icon-light-fg-error) / <alpha-value>)",
                    warning: "rgb(var(--colors-featured-icon-light-fg-warning) / <alpha-value>)",
                    success: "rgb(var(--colors-featured-icon-light-fg-success) / <alpha-value>)",
                },
            },
            dark: {
                fg: {
                    brand: "rgb(var(--colors-featured-icon-dark-fg-brand) / <alpha-value>)",
                    gray: "rgb(var(--colors-featured-icon-dark-fg-gray) / <alpha-value>)",
                    error: "rgb(var(--colors-featured-icon-dark-fg-error) / <alpha-value>)",
                    warning: "rgb(var(--colors-featured-icon-dark-fg-warning) / <alpha-value>)",
                    success: "rgb(var(--colors-featured-icon-dark-fg-success) / <alpha-value>)",
                },
            },
            modern: {
                border: "rgb(var(--colors-featured-icon-modern-border) / <alpha-value>)",
            },
        },
        "social-icon": {
            fg: {
                x: "rgb(var(--colors-social-icon-fg-x) / <alpha-value>)",
                instagram: "rgb(var(--colors-social-icon-fg-instagram) / <alpha-value>)",
                apple: "rgb(var(--colors-social-icon-fg-apple) / <alpha-value>)",
                github: "rgb(var(--colors-social-icon-fg-github) / <alpha-value>)",
                angellist: "rgb(var(--colors-social-icon-fg-angellist) / <alpha-value>)",
                tumblr: "rgb(var(--colors-social-icon-fg-tumblr) / <alpha-value>)",
            },
        },
        "screen-mockup": {
            border: "rgb(var(--colors-screen-mockup-border) / <alpha-value>)",
        },
        "slider-handle": {
            bg: "rgb(var(--colors-slider-handle-bg) / <alpha-value>)",
            border: "rgb(var(--colors-slider-handle-border) / <alpha-value>)",
        },
        "thumbnail-badge": {
            brand: {
                fg: "rgb(var(--colors-thumbnail-badge-brand-fg) / <alpha-value>)",
            },
            success: {
                fg: "rgb(var(--colors-thumbnail-badge-success-fg) / <alpha-value>)",
            },
        },
        toggle: {
            button: {
                fg_disabled: "rgb(var(--colors-toggle-button-fg_disabled) / <alpha-value>)",
            },
        },
        "wysiwyg-editor-icon": {
            fg: "rgb(var(--colors-wysiwyg-editor-icon-fg) / <alpha-value>)",
            fg_active: "rgb(var(--colors-wysiwyg-editor-icon-fg_active) / <alpha-value>)",
        },
    },
};
