import '../styles/globals.min.css';
import '../styles/inter.min.css';
import '../styles/theme.min.css';
import '../styles/colors.min.css';
import '../styles/manrope.min.css';
import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import { Theme } from '@/providers/theme-provider';
import { cx } from '@/components/utils';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
  display: 'swap',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  themeColor: '#7f56d9',
  colorScheme: 'dark light',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning>
      <body
        className={cx(
          geistSans.variable,
          geistMono.variable,
          'antialiased bg-primary'
        )}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
